### ISSUE TITLE
编译之后 用AUTO 生成代码 会触发一个重复的KEY 问题

### ISSUE THREAD

**Issue by zero16832** [sdcb/FFmpeg.AutoGen#16]
av_image_copy2
这个 会有多个

Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: av_image_copy2
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Sdcb.FFmpeg.AutoGen.Generator.WriteInlineFunctions(String outputFile) in F:\Sdcb.FFmpeg\src\Sdcb.FFmpeg.AutoGen\Generator.cs:line 150
   at Sdcb.FFmpeg.AutoGen.Program.Main(String[] args) in F:\Sdcb.FFmpeg\src\Sdcb.FFmpeg.AutoGen\Program.cs:line 98

**Comment by sdcb** [comment]
按道理你没必要自行运行AutoGen项目，因为它是根据最新的头文件去创建的

**Comment by zero16832** [comment]
我就跑了一下 试试 看看啥效果 ,我看了一下 有可能是这里导致的：/**
 * Copy image in src_data to dst_data.
 *
 * @param dst_data      destination image data buffer to copy to
 * @param dst_linesizes linesizes for the image in dst_data
 * @param src_data      source image data buffer to copy from
 * @param src_linesizes linesizes for the image in src_data
 * @param pix_fmt       the AVPixelFormat of the image
 * @param width         width of the image in pixels
 * @param height        height of the image in pixels
 */
void av_image_copy(uint8_t * const dst_data[4], const int dst_linesizes[4],
                   const uint8_t * const src_data[4], const int src_linesizes[4],
                   enum AVPixelFormat pix_fmt, int width, int height);

/**
 * Wrapper around av_image_copy() to workaround the limitation
 * that the conversion from uint8_t * const * to const uint8_t * const *
 * is not performed automatically in C.
 * @see av_image_copy()
 */
static inline
void av_image_copy2(uint8_t * const dst_data[4], const int dst_linesizes[4],
                    uint8_t * const src_data[4], const int src_linesizes[4],
                    enum AVPixelFormat pix_fmt, int width, int height)
{
    av_image_copy(dst_data, dst_linesizes,
                  (const uint8_t * const *)src_data, src_linesizes,
                  pix_fmt, width, height);
} 
libavutil/imgutils.h

**Comment by zero16832** [comment]
上面的内容 就是 最新的ffmpeg-release-full-shared.7z 里面的文件的内容

**Comment by sdcb** [comment]
是的，最新的ffmpeg包可能会随着里面内容的变化导致原本的解析代码失效

**Comment by zero16832** [comment]
有空 麻烦 看看？

**Comment by sdcb** [comment]
fixed in https://github.com/sdcb/Sdcb.FFmpeg/commit/9861d93d943b927d0c7d0a0a70f0aae7814811a2
