### ISSUE TITLE
[FFmpeg error -2]: No such file or directory

### ISSUE THREAD

**Issue by nowayout** [sdcb/FFmpeg.AutoGen#24]
[FFmpeg error -2]: No such file or directory
用下面的代码列出USB摄像头，报错
var dict = new MediaDictionary();
dict.Set("list_devices", "true", 0);
using FormatContext inFc = FormatContext.OpenInputUrl("video=dummy", InputFormat.FindByShortName("dshow"), dict);
inFc.LoadStreamInfo();

**Comment by nowayout** [comment]
就是相当于这个命令
ffmpeg.exe -list_devices true -f dshow -i dummy

**Comment by Tzeross** [comment]
请教怎么解决
